// ── Testimonial types ───────────────────────────────────────────────
//
// The Supabase table `public.testimonials` stores columns named
// `name / designation / company / testimonial / avatar`, while the UI
// components work with `author / role / quote / emoji`. The service layer
// maps between the two so the existing UI stays byte-for-byte identical.

// NOTE: these three are declared as `type` (not `interface`) on purpose —
// supabase-js constrains table schemas to `Record<string, unknown>`, and only
// type aliases satisfy that constraint (interfaces are open to augmentation and
// don't). Using `interface` here makes the client fall back to `never`.

/** A row exactly as stored in `public.testimonials`. */
export type TestimonialRow = {
  id: string;
  name: string;
  designation: string | null;
  company: string | null;
  testimonial: string;
  avatar: string | null;
  approved: boolean;
  created_at: string;
};

/** Fields required to insert a new row (id / created_at are generated by the DB). */
export type TestimonialInsert = {
  name: string;
  designation: string | null;
  company: string | null;
  testimonial: string;
  avatar: string | null;
  approved: boolean;
};

/** Fields the app is allowed to update. */
export type TestimonialUpdate = {
  name?: string;
  designation?: string | null;
  company?: string | null;
  testimonial?: string;
  avatar?: string | null;
  approved?: boolean;
};

/** Shape consumed by the public-facing UI (unchanged from the original site). */
export interface Testimonial {
  id: string;
  quote: string;
  author: string;
  role: string;
  emoji: string;
}

/** Shape consumed by the admin dashboard (adds moderation metadata). */
export interface AdminTestimonial extends Testimonial {
  approved: boolean;
  createdAt: string;
}

/** Payload a visitor submits from the "Leave a Testimonial" form. */
export interface NewTestimonialInput {
  quote: string;
  author: string;
  role: string;
  emoji: string;
}

/**
 * Typed schema so `createClient<Database>` is fully type-safe. The shape mirrors
 * what Supabase's type generator emits (Tables/Views/Functions/Enums/
 * CompositeTypes + per-table Relationships) so the client infers Insert/Update
 * payloads correctly instead of falling back to `never`.
 */
export interface Database {
  public: {
    Tables: {
      testimonials: {
        Row: TestimonialRow;
        Insert: TestimonialInsert;
        Update: TestimonialUpdate;
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
}
